name: "planejamento_caixa"
version: "1.0.0"
config-version: 2

profile: "planejamento_caixa"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  planejamento_caixa:
    staging:
      +materialized: view
    marts:
      +materialized: table
